cabal-version:       2.2

name:                voidtalon
version:             0.1.0.0
homepage:            https://git.mzte.de/LordMZTE/voidtalon
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              LordMZTE
maintainer:          lord@mzte.de
build-type:          Simple
extra-source-files:  README.md

executable vt
  other-modules:
      VoidTalon.CLI
      VoidTalon.Config
      VoidTalon.Net
      VoidTalon.Net.Completions
      VoidTalon.TUI
      VoidTalon.TUI.Timeline
      VoidTalon.TUI.Types
      VoidTalon.Timeline
  hs-source-dirs:      src
  main-is:             VoidTalon/Main.hs
  default-language:    Haskell2010
  build-depends:
      , aeson
      , base
      , brick
      , bytestring
      , containers
      , directory
      , filepath
      , http-client
      , http-types
      , microlens
      , microlens-mtl
      , microlens-th
      , network-uri
      , optparse-applicative
      , text
      , text-zipper
      , toml-parser
      , vty
  ghc-options: -Wall
               -Wcompat
               -Widentities
               -Wincomplete-record-updates
               -Wincomplete-uni-patterns
               -Wincomplete-patterns
               -Wmissing-export-lists
               -Wmissing-home-modules
               -Wredundant-constraints

               -main-is VoidTalon.Main

               -- Needed for Brick
               -threaded
  default-extensions:
    OverloadedRecordDot
    NamedFieldPuns
    NoFieldSelectors

source-repository head
  type:     git
  location: https://git.mzte.de/LordMZTE/voidtalon
